openapi: 3.0.0
info:
  title: CareConnect API
  version: 1.0.0
  description: API documentation for CareConnect Healthcare System

servers:
  - url: http://localhost:5000

paths:
  /api/auth/register:
    post:
      summary: Register a new user (patient or doctor)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
                - name
                - email
                - password
                - role
      responses:
        '201':
          description: User registered successfully
        '400':
          description: User already exists

  /api/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Returns JWT token
        '400':
          description: Invalid credentials

  /api/clinics:
    get:
      summary: Search for nearby clinics
      parameters:
        - in: query
          name: lat
          schema:
            type: string
          required: true
        - in: query
          name: lng
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of nearby clinics

  /api/appointments/book:
    post:
      summary: Book an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctorId:
                  type: string
                patientId:
                  type: string
                date:
                  type: string
                time:
                  type: string
              required:
                - doctorId
                - patientId
                - date
                - time
      responses:
        '201':
          description: Appointment booked

  /api/documents/upload:
    post:
      summary: Upload a medical document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                patientId:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Document uploaded successfully
